CPP_FLAGS='-std=c++17'

#main:LinuxSystemCode.h main.cpp
#	g++ ${CPP_FLAGS} -o main LinuxSystemCode.h main.cpp


server: TCP_Servicer_demo1.cpp
	g++  ${CPP_FLAGS} -o server TCP_Servicer_demo1.cpp

client: TCP_Client_demo1.cpp
	g++  ${CPP_FLAGS} -o server TCP_Client_demo1.cpp