CPP_FLAGS='-std=c++17'

main:UnixDemo1.h UnixDemo1.cpp
	g++ ${CPP_FLAGS} -o main UnixDemo1.h UnixDemo1.cpp

#hello:hello.o
#	gcc hello.o -o hello
#
#hello.o:hello.S
#	gcc -c hello.S -o hello.o
#
#hello.S:hello.i
#	gcc -S hello.i -o hello.S
#
#hello.i:hello.c
#	gcc -E hello.c -o hello.i
#.PHONY:
#clear:
#	rm hello.o hello.S hello.i