---
--- Generated by Luanalysis
--- Created by XMZR.
--- DateTime: 2022/8/30 14:07
---

print("hello lua world")

function f(value)
    if value <= 1 then
        return 1
    end
    return f(value - 1) + value
end
print(f(10))

list = { 1, 23, 4, 2, 5, 4, 6 }
function f2(list)
    for i = 1, #list - 1 do
        for p = i + 1, #list do
            if list[i] > list[p] then
                var = list[p]
                list[p] = list[i]
                list[i] = var
            end
        end
    end
    return list
end

function cout(list)
    s = ""
    for i = 1, #list do
        s = s .. list[i] .. " "
    end
    print(s)
end

cout(list)
cout(f2(list))

table = {
    "wenhao",
    20,
    {
        100,
        {
            "风暴之锤",
            "黑暗之门",
        }
    }
}

print(table[3][2][1]);