---
--- Generated by Luanalysis
--- Created by XMZR.
--- DateTime: 2022/8/30 14:07
---

print("Hello Lua World")
function f(value)
    if value <= 1 then
        return 1
    end
    return f(value - 1) + value
end
function f2(list)
    for i = 1, #list - 1 do
        for p = i + 1, #list do
            if list[i] > list[p] then
                var = list[p]
                list[p] = list[i]
                list[i] = var
            end
        end
    end
    return list
end
function cout(list)
    s = ""
    for i = 1, #list do
        s = s .. list[i] .. " "
    end
    return s
end

list = { 6, 13, 4, 9, 5, 2, 7 }
print("从1加到10: "..f(10))
print("排序前: "..cout(list))
print("排序后: "..cout(f2(list)))

table = {
    "wenhao",
    20,
    {
        100,
        {
            "风暴之锤",
            "黑暗之门",
        }
    }
}
print("table[3][2][1] : "..table[3][2][1]);

name = "wenhao" age = 128