---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by XMZR.
--- DateTime: 2022/9/16 14:27
---

name = "bob"
age = 20
mystr = "hello lua"
mytable = { name = "tom", id = 123456 }

function add(x, y)
    return 2 * x + y
end

function add2(x, y)
    return x * y
end