---
--- Generated by EmmyLua(https:/github.com/EmmyLua)
--- Created by XMZR.
--- DateTime: 2022/9/28 14:48
---

package.path = package.path..";/D:/Users/XMZR/CLionProjects/Splicing-bit-fragments/Main_c_modules/LuaAndCorCpp/BusinessModules/LuaCatalogue/?.lua"

--local a = dofile("D:/Users/XMZR/CLionProjects/Splicing-bit-fragments/Main_c_modules/LuaAndCorCpp/BusinessModules/LuaCatalogue/algorithm.lua")
local a = require("algorithm")
print(a.var)


