---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 20106.
--- DateTime: 2022/10/31 17:00
---
-- 简单模式
-- 以只读方式打开文件
file = io.open("./wenben.txt", "r")
-- 设置默认输入文件为 test.lua
io.input(file)
-- 输出文件第一行
print(io.read())
-- 关闭打开的文件
io.close(file)

---- 以附加的方式打开只写文件
--file = io.open("./wenben.txt", "a")
---- 设置默认输出文件为 test.lua
--io.output(file)
---- 在文件最后一行添加 Lua 注释
--io.write("--  test.lua 文件末尾注释")
---- 关闭打开的文件
--io.close(file)
